
package com.landa.material.action.struts;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MaterialAction", targetNamespace = "http://struts.action.material.landa.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MaterialAction {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getImageId", targetNamespace = "http://struts.action.material.landa.com/", className = "com.landa.material.action.struts.GetImageId")
    @ResponseWrapper(localName = "getImageIdResponse", targetNamespace = "http://struts.action.material.landa.com/", className = "com.landa.material.action.struts.GetImageIdResponse")
    @Action(input = "http://struts.action.material.landa.com/MaterialAction/getImageIdRequest", output = "http://struts.action.material.landa.com/MaterialAction/getImageIdResponse")
    public String getImageId();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setImageId", targetNamespace = "http://struts.action.material.landa.com/", className = "com.landa.material.action.struts.SetImageId")
    @ResponseWrapper(localName = "setImageIdResponse", targetNamespace = "http://struts.action.material.landa.com/", className = "com.landa.material.action.struts.SetImageIdResponse")
    @Action(input = "http://struts.action.material.landa.com/MaterialAction/setImageIdRequest", output = "http://struts.action.material.landa.com/MaterialAction/setImageIdResponse")
    public void setImageId(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.landa.material.action.struts.Material>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMaterials", targetNamespace = "http://struts.action.material.landa.com/", className = "com.landa.material.action.struts.GetMaterials")
    @ResponseWrapper(localName = "getMaterialsResponse", targetNamespace = "http://struts.action.material.landa.com/", className = "com.landa.material.action.struts.GetMaterialsResponse")
    @Action(input = "http://struts.action.material.landa.com/MaterialAction/getMaterialsRequest", output = "http://struts.action.material.landa.com/MaterialAction/getMaterialsResponse")
    public List<Material> getMaterials();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setMaterials", targetNamespace = "http://struts.action.material.landa.com/", className = "com.landa.material.action.struts.SetMaterials")
    @ResponseWrapper(localName = "setMaterialsResponse", targetNamespace = "http://struts.action.material.landa.com/", className = "com.landa.material.action.struts.SetMaterialsResponse")
    @Action(input = "http://struts.action.material.landa.com/MaterialAction/setMaterialsRequest", output = "http://struts.action.material.landa.com/MaterialAction/setMaterialsResponse")
    public void setMaterials(
        @WebParam(name = "arg0", targetNamespace = "")
        List<Material> arg0);

    /**
     * 
     * @return
     *     returns com.landa.material.action.struts.MaterialPageInfo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPageInfo", targetNamespace = "http://struts.action.material.landa.com/", className = "com.landa.material.action.struts.GetPageInfo")
    @ResponseWrapper(localName = "getPageInfoResponse", targetNamespace = "http://struts.action.material.landa.com/", className = "com.landa.material.action.struts.GetPageInfoResponse")
    @Action(input = "http://struts.action.material.landa.com/MaterialAction/getPageInfoRequest", output = "http://struts.action.material.landa.com/MaterialAction/getPageInfoResponse")
    public MaterialPageInfo getPageInfo();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setMaterial", targetNamespace = "http://struts.action.material.landa.com/", className = "com.landa.material.action.struts.SetMaterial")
    @ResponseWrapper(localName = "setMaterialResponse", targetNamespace = "http://struts.action.material.landa.com/", className = "com.landa.material.action.struts.SetMaterialResponse")
    @Action(input = "http://struts.action.material.landa.com/MaterialAction/setMaterialRequest", output = "http://struts.action.material.landa.com/MaterialAction/setMaterialResponse")
    public void setMaterial(
        @WebParam(name = "arg0", targetNamespace = "")
        Material arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "materialSave", targetNamespace = "http://struts.action.material.landa.com/", className = "com.landa.material.action.struts.MaterialSave")
    @ResponseWrapper(localName = "materialSaveResponse", targetNamespace = "http://struts.action.material.landa.com/", className = "com.landa.material.action.struts.MaterialSaveResponse")
    @Action(input = "http://struts.action.material.landa.com/MaterialAction/materialSaveRequest", output = "http://struts.action.material.landa.com/MaterialAction/materialSaveResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://struts.action.material.landa.com/MaterialAction/materialSave/Fault/Exception")
    })
    public String materialSave()
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "viewMaterial", targetNamespace = "http://struts.action.material.landa.com/", className = "com.landa.material.action.struts.ViewMaterial")
    @ResponseWrapper(localName = "viewMaterialResponse", targetNamespace = "http://struts.action.material.landa.com/", className = "com.landa.material.action.struts.ViewMaterialResponse")
    @Action(input = "http://struts.action.material.landa.com/MaterialAction/viewMaterialRequest", output = "http://struts.action.material.landa.com/MaterialAction/viewMaterialResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://struts.action.material.landa.com/MaterialAction/viewMaterial/Fault/Exception")
    })
    public String viewMaterial()
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "goImageView", targetNamespace = "http://struts.action.material.landa.com/", className = "com.landa.material.action.struts.GoImageView")
    @ResponseWrapper(localName = "goImageViewResponse", targetNamespace = "http://struts.action.material.landa.com/", className = "com.landa.material.action.struts.GoImageViewResponse")
    @Action(input = "http://struts.action.material.landa.com/MaterialAction/goImageViewRequest", output = "http://struts.action.material.landa.com/MaterialAction/goImageViewResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://struts.action.material.landa.com/MaterialAction/goImageView/Fault/Exception")
    })
    public String goImageView()
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "materialList", targetNamespace = "http://struts.action.material.landa.com/", className = "com.landa.material.action.struts.MaterialList")
    @ResponseWrapper(localName = "materialListResponse", targetNamespace = "http://struts.action.material.landa.com/", className = "com.landa.material.action.struts.MaterialListResponse")
    @Action(input = "http://struts.action.material.landa.com/MaterialAction/materialListRequest", output = "http://struts.action.material.landa.com/MaterialAction/materialListResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://struts.action.material.landa.com/MaterialAction/materialList/Fault/Exception")
    })
    public String materialList()
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns com.landa.material.action.struts.Material
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMaterial", targetNamespace = "http://struts.action.material.landa.com/", className = "com.landa.material.action.struts.GetMaterial")
    @ResponseWrapper(localName = "getMaterialResponse", targetNamespace = "http://struts.action.material.landa.com/", className = "com.landa.material.action.struts.GetMaterialResponse")
    @Action(input = "http://struts.action.material.landa.com/MaterialAction/getMaterialRequest", output = "http://struts.action.material.landa.com/MaterialAction/getMaterialResponse")
    public Material getMaterial();

    /**
     * 
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "materialImageRemove", targetNamespace = "http://struts.action.material.landa.com/", className = "com.landa.material.action.struts.MaterialImageRemove")
    @ResponseWrapper(localName = "materialImageRemoveResponse", targetNamespace = "http://struts.action.material.landa.com/", className = "com.landa.material.action.struts.MaterialImageRemoveResponse")
    @Action(input = "http://struts.action.material.landa.com/MaterialAction/materialImageRemoveRequest", output = "http://struts.action.material.landa.com/MaterialAction/materialImageRemoveResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://struts.action.material.landa.com/MaterialAction/materialImageRemove/Fault/Exception")
    })
    public String materialImageRemove()
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "goMaterialEdit", targetNamespace = "http://struts.action.material.landa.com/", className = "com.landa.material.action.struts.GoMaterialEdit")
    @ResponseWrapper(localName = "goMaterialEditResponse", targetNamespace = "http://struts.action.material.landa.com/", className = "com.landa.material.action.struts.GoMaterialEditResponse")
    @Action(input = "http://struts.action.material.landa.com/MaterialAction/goMaterialEditRequest", output = "http://struts.action.material.landa.com/MaterialAction/goMaterialEditResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://struts.action.material.landa.com/MaterialAction/goMaterialEdit/Fault/Exception")
    })
    public String goMaterialEdit()
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod(operationName = "InquiryBaanService")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "InquiryBaanService", targetNamespace = "http://struts.action.material.landa.com/", className = "com.landa.material.action.struts.InquiryBaanService")
    @ResponseWrapper(localName = "InquiryBaanServiceResponse", targetNamespace = "http://struts.action.material.landa.com/", className = "com.landa.material.action.struts.InquiryBaanServiceResponse")
    @Action(input = "http://struts.action.material.landa.com/MaterialAction/InquiryBaanServiceRequest", output = "http://struts.action.material.landa.com/MaterialAction/InquiryBaanServiceResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://struts.action.material.landa.com/MaterialAction/InquiryBaanService/Fault/Exception")
    })
    public String inquiryBaanService()
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod(operationName = "InquiryBaanServiceToVue")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "InquiryBaanServiceToVue", targetNamespace = "http://struts.action.material.landa.com/", className = "com.landa.material.action.struts.InquiryBaanServiceToVue")
    @ResponseWrapper(localName = "InquiryBaanServiceToVueResponse", targetNamespace = "http://struts.action.material.landa.com/", className = "com.landa.material.action.struts.InquiryBaanServiceToVueResponse")
    @Action(input = "http://struts.action.material.landa.com/MaterialAction/InquiryBaanServiceToVueRequest", output = "http://struts.action.material.landa.com/MaterialAction/InquiryBaanServiceToVueResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://struts.action.material.landa.com/MaterialAction/InquiryBaanServiceToVue/Fault/Exception")
    })
    public String inquiryBaanServiceToVue(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<com.landa.material.action.struts.Material>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "materialListToVue", targetNamespace = "http://struts.action.material.landa.com/", className = "com.landa.material.action.struts.MaterialListToVue")
    @ResponseWrapper(localName = "materialListToVueResponse", targetNamespace = "http://struts.action.material.landa.com/", className = "com.landa.material.action.struts.MaterialListToVueResponse")
    @Action(input = "http://struts.action.material.landa.com/MaterialAction/materialListToVueRequest", output = "http://struts.action.material.landa.com/MaterialAction/materialListToVueResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://struts.action.material.landa.com/MaterialAction/materialListToVue/Fault/Exception")
    })
    public List<Material> materialListToVue(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "materialJsonList", targetNamespace = "http://struts.action.material.landa.com/", className = "com.landa.material.action.struts.MaterialJsonList")
    @ResponseWrapper(localName = "materialJsonListResponse", targetNamespace = "http://struts.action.material.landa.com/", className = "com.landa.material.action.struts.MaterialJsonListResponse")
    @Action(input = "http://struts.action.material.landa.com/MaterialAction/materialJsonListRequest", output = "http://struts.action.material.landa.com/MaterialAction/materialJsonListResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://struts.action.material.landa.com/MaterialAction/materialJsonList/Fault/Exception")
    })
    public String materialJsonList()
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod(operationName = "InquiryWMSService")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "InquiryWMSService", targetNamespace = "http://struts.action.material.landa.com/", className = "com.landa.material.action.struts.InquiryWMSService")
    @ResponseWrapper(localName = "InquiryWMSServiceResponse", targetNamespace = "http://struts.action.material.landa.com/", className = "com.landa.material.action.struts.InquiryWMSServiceResponse")
    @Action(input = "http://struts.action.material.landa.com/MaterialAction/InquiryWMSServiceRequest", output = "http://struts.action.material.landa.com/MaterialAction/InquiryWMSServiceResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://struts.action.material.landa.com/MaterialAction/InquiryWMSService/Fault/Exception")
    })
    public String inquiryWMSService()
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod(operationName = "InquiryFP7Service")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "InquiryFP7Service", targetNamespace = "http://struts.action.material.landa.com/", className = "com.landa.material.action.struts.InquiryFP7Service")
    @ResponseWrapper(localName = "InquiryFP7ServiceResponse", targetNamespace = "http://struts.action.material.landa.com/", className = "com.landa.material.action.struts.InquiryFP7ServiceResponse")
    @Action(input = "http://struts.action.material.landa.com/MaterialAction/InquiryFP7ServiceRequest", output = "http://struts.action.material.landa.com/MaterialAction/InquiryFP7ServiceResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://struts.action.material.landa.com/MaterialAction/InquiryFP7Service/Fault/Exception")
    })
    public String inquiryFP7Service()
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOrderIndexs", targetNamespace = "http://struts.action.material.landa.com/", className = "com.landa.material.action.struts.GetOrderIndexs")
    @ResponseWrapper(localName = "getOrderIndexsResponse", targetNamespace = "http://struts.action.material.landa.com/", className = "com.landa.material.action.struts.GetOrderIndexsResponse")
    @Action(input = "http://struts.action.material.landa.com/MaterialAction/getOrderIndexsRequest", output = "http://struts.action.material.landa.com/MaterialAction/getOrderIndexsResponse")
    public String getOrderIndexs();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setOrderIndexs", targetNamespace = "http://struts.action.material.landa.com/", className = "com.landa.material.action.struts.SetOrderIndexs")
    @ResponseWrapper(localName = "setOrderIndexsResponse", targetNamespace = "http://struts.action.material.landa.com/", className = "com.landa.material.action.struts.SetOrderIndexsResponse")
    @Action(input = "http://struts.action.material.landa.com/MaterialAction/setOrderIndexsRequest", output = "http://struts.action.material.landa.com/MaterialAction/setOrderIndexsResponse")
    public void setOrderIndexs(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setPageInfo", targetNamespace = "http://struts.action.material.landa.com/", className = "com.landa.material.action.struts.SetPageInfo")
    @ResponseWrapper(localName = "setPageInfoResponse", targetNamespace = "http://struts.action.material.landa.com/", className = "com.landa.material.action.struts.SetPageInfoResponse")
    @Action(input = "http://struts.action.material.landa.com/MaterialAction/setPageInfoRequest", output = "http://struts.action.material.landa.com/MaterialAction/setPageInfoResponse")
    public void setPageInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        MaterialPageInfo arg0);

}
