
package com.landa.material.action.struts;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MaterialActionService", targetNamespace = "http://struts.action.material.landa.com/", wsdlLocation = "http://localhost:8081/ws?wsdl")
public class MaterialActionService
    extends Service
{

    private final static URL MATERIALACTIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException MATERIALACTIONSERVICE_EXCEPTION;
    private final static QName MATERIALACTIONSERVICE_QNAME = new QName("http://struts.action.material.landa.com/", "MaterialActionService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/ws?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MATERIALACTIONSERVICE_WSDL_LOCATION = url;
        MATERIALACTIONSERVICE_EXCEPTION = e;
    }

    public MaterialActionService() {
        super(__getWsdlLocation(), MATERIALACTIONSERVICE_QNAME);
    }

    public MaterialActionService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MATERIALACTIONSERVICE_QNAME, features);
    }

    public MaterialActionService(URL wsdlLocation) {
        super(wsdlLocation, MATERIALACTIONSERVICE_QNAME);
    }

    public MaterialActionService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MATERIALACTIONSERVICE_QNAME, features);
    }

    public MaterialActionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MaterialActionService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MaterialAction
     */
    @WebEndpoint(name = "MaterialActionPort")
    public MaterialAction getMaterialActionPort() {
        return super.getPort(new QName("http://struts.action.material.landa.com/", "MaterialActionPort"), MaterialAction.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MaterialAction
     */
    @WebEndpoint(name = "MaterialActionPort")
    public MaterialAction getMaterialActionPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://struts.action.material.landa.com/", "MaterialActionPort"), MaterialAction.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MATERIALACTIONSERVICE_EXCEPTION!= null) {
            throw MATERIALACTIONSERVICE_EXCEPTION;
        }
        return MATERIALACTIONSERVICE_WSDL_LOCATION;
    }

}
